# Unique project key (use lowercase, no spaces)
sonar.projectKey=reddit

# Only required for SonarCloud
sonar.organization=https://sonarcloud.io/organizations/dhuriyapawan/projects

# Project name and version
sonar.projectName=Reddit Project
sonar.projectVersion=1.0

# Source code folder
sonar.sources=.

# Host and login token (environment variables)
sonar.host.url=${SONAR_HOST_URL}
sonar.login=${SONAR_TOKEN}