name: Reddit App Deployment

on : 
    push :
        branches:
            - main

jobs: 
    build-and-deploy:
        name : Build and Deploy aws terraform
        runs-on : ubuntu-latest
        steps:
        - name : checkout code
          uses: actions/checkout@v2
          with :
             fetch-depth: 0

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
             node-version: '18'

        - name: Install dependencies
          run : npm install
        
        - name: Run build
          run: npm run build

        - name: Set Up JDK
          uses : actions/setup-java@v4
          with :
            java-version : '17'
            distribution: 'temurin'
        
        - name : Install Trivy
          run: |
                 sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
                 wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
                 echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
                 sudo apt-get update
                 sudo apt-get install -y trivy

        - name: Run Trivy Scan
          run: |
               # Scan project dependencies
               trivy fs --exit-code 1 --severity HIGH,CRITICAL .
          # Optionally, scan Docker image if you build one
          # trivy image --exit-code 1 --severity HIGH,CRITICAL my-app:latest

        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v2
          env:
             SONAR_TOKEN : ${{secrets.SONAR_TOKEN}}
             SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
             SONAR_PROJECT_KEY: dhuriyapawan_Reddit       # must match project key on SonarCloud
             SONAR_ORGANIZATION: https://sonarcloud.io

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region : ${{secrets.AWS_REGION}}


        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

      # 3️⃣ Pull OWASP Dependency-Check image
        - name: Pull OWASP Dependency-Check Docker
          run: docker pull owasp/dependency-check:latest

      # 4️⃣ Build your application Docker image
        - name: Build application Docker image
          run: docker build -t reddit:latest .

      
